version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf  # Monta la configuración de Apache
    environment:
      - TZ=America/Mexico_City  # Configura la zona horaria para Apache
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'fut7'
      MYSQL_USER: 'aaron'
      MYSQL_PASSWORD: 'creativo'
      MYSQL_ROOT_PASSWORD: 'creativo'
      TZ: 'America/Mexico_City'  # Configura la zona horaria para MySQL
    # ports:
    #   - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
